export const jobTypeOptions = [
  { value: "Full_time", label: "Full-time" },
  { value: "Part_time", label: "Part-time" },
  { value: "Contract", label: "Contract" },
  { value: "Internship", label: "Internship" },
];

export const educationLevelOptions = [
  { value: "High_School_Diploma", label: "High School Diploma" },
  { value: "Associates_Degree", label: "Associate's Degree" },
  { value: "Bachelors_Degree", label: "Bachelor's Degree" },
  { value: "Masters_Degree", label: "Master's Degree" },
  { value: "PhD", label: "PhD" },
  { value: "Other", label: "Other" },
];

export const statusOptions = [
  { value: "Open", label: "Open" },
  { value: "Closed", label: "Closed" },
];

export const skillOptions = [
  { value: "JavaScript_TypeScript", label: "JavaScript/TypeScript" },
  { value: "Python", label: "Python" },
  { value: "Java", label: "Java" },
  { value: "CSharp", label: "C#" },
  { value: "C_CPlusPlus", label: "C/C++" },
  { value: "Go_Golang", label: "Go/Golang" },
  { value: "Rust", label: "Rust" },
  { value: "Kotlin", label: "Kotlin" },
  { value: "Swift", label: "Swift" },
  { value: "PHP", label: "PHP" },
  { value: "Ruby", label: "Ruby" },
  { value: "Scala", label: "Scala" },
  { value: "Dart", label: "Dart" },
  { value: "R", label: "R" },
  { value: "Elixir", label: "Elixir" },
  { value: "Perl", label: "Perl" },
  { value: "Frontend_Development", label: "Frontend Development" },
  { value: "ReactJS", label: "ReactJS" },
  { value: "Angular", label: "Angular" },
  { value: "VueJS", label: "VueJS" },
  { value: "Svelte", label: "Svelte" },
  { value: "NextJS", label: "NextJS" },
  { value: "NuxtJS", label: "NuxtJS" },
  { value: "HTML_CSS", label: "HTML/CSS" },
  { value: "Tailwind_CSS", label: "Tailwind CSS" },
  { value: "Bootstrap", label: "Bootstrap" },
  { value: "WebAssembly", label: "WebAssembly" },
  { value: "Backend_Development", label: "Backend Development" },
  { value: "NodeJS", label: "NodeJS" },
  { value: "ExpressJS", label: "ExpressJS" },
  { value: "Django", label: "Django" },
  { value: "Flask", label: "Flask" },
  { value: "FastAPI", label: "FastAPI" },
  { value: "Spring_Boot", label: "Spring Boot" },
  { value: "Laravel", label: "Laravel" },
  { value: "Ruby_on_Rails", label: "Ruby on Rails" },
  { value: "ASP_NET", label: "ASP.NET" },
  { value: "NestJS", label: "NestJS" },
  { value: "GraphQL", label: "GraphQL" },
  { value: "REST_APIs", label: "REST APIs" },
  { value: "React_Native", label: "React Native" },
  { value: "Flutter", label: "Flutter" },
  { value: "Swift_iOS", label: "Swift (iOS)" },
  { value: "Kotlin_Android", label: "Kotlin (Android)" },
  { value: "Xamarin", label: "Xamarin" },
  { value: "Ionic", label: "Ionic" },
  { value: "PostgreSQL", label: "PostgreSQL" },
  { value: "MySQL", label: "MySQL" },
  { value: "MongoDB", label: "MongoDB" },
  { value: "Firebase", label: "Firebase" },
  { value: "SQLite", label: "SQLite" },
  { value: "Microsoft_SQL_Server", label: "Microsoft SQL Server" },
  { value: "Oracle_DB", label: "Oracle DB" },
  { value: "Cassandra", label: "Cassandra" },
  { value: "Redis", label: "Redis" },
  { value: "DynamoDB", label: "DynamoDB" },
  { value: "Neo4j_Graph_DB", label: "Neo4j Graph DB" },
  { value: "AWS_Amazon_Web_Services", label: "AWS" },
  { value: "Azure", label: "Azure" },
  { value: "Google_Cloud_GCP", label: "Google Cloud" },
  { value: "Docker", label: "Docker" },
  { value: "Kubernetes", label: "Kubernetes" },
  { value: "Terraform", label: "Terraform" },
  { value: "Ansible", label: "Ansible" },
  { value: "Jenkins", label: "Jenkins" },
  { value: "GitHub_Actions", label: "GitHub Actions" },
  { value: "CI_CD_Pipelines", label: "CI/CD Pipelines" },
  { value: "Serverless_AWS_Lambda_Azure_Functions", label: "Serverless" },
  { value: "AI_ML_Data_Science", label: "AI/ML/Data Science" },
  { value: "TensorFlow", label: "TensorFlow" },
  { value: "PyTorch", label: "PyTorch" },
  { value: "Scikit_learn", label: "Scikit-learn" },
  { value: "Keras", label: "Keras" },
  { value: "OpenAI_GPT", label: "OpenAI GPT" },
  { value: "LangChain", label: "LangChain" },
  { value: "Hugging_Face", label: "Hugging Face" },
  { value: "Pandas", label: "Pandas" },
  { value: "NumPy", label: "NumPy" },
  { value: "Apache_Spark", label: "Apache Spark" },
  { value: "Hadoop", label: "Hadoop" },
  { value: "Blockchain_Web3", label: "Blockchain/Web3" },
  { value: "Solidity", label: "Solidity" },
  { value: "Ethereum", label: "Ethereum" },
  { value: "Polygon", label: "Polygon" },
  { value: "Solana", label: "Solana" },
  { value: "Hyperledger", label: "Hyperledger" },
  { value: "Web3JS_EthersJS", label: "Web3.js/Ethers.js" },
  { value: "Cybersecurity_General", label: "Cybersecurity" },
  { value: "Penetration_Testing", label: "Penetration Testing" },
  { value: "Ethical_Hacking", label: "Ethical Hacking" },
  { value: "SIEM_Tools_Splunk_Wazuh", label: "SIEM Tools" },
  { value: "Cryptography", label: "Cryptography" },
  { value: "Zero_Trust_Security", label: "Zero Trust Security" },
  { value: "Game_Development", label: "Game Development" },
  { value: "Unity", label: "Unity" },
  { value: "Unreal_Engine", label: "Unreal Engine" },
  { value: "Godot", label: "Godot" },
  { value: "Phaser", label: "Phaser" },
  { value: "Others", label: "Others" },
  { value: "IoT_Internet_of_Things", label: "IoT" },
  { value: "AR_VR_Augmented_Virtual_Reality", label: "AR/VR" },
  { value: "Embedded_Systems", label: "Embedded Systems" },
  { value: "Robotics", label: "Robotics" },
  { value: "Quantum_Computing", label: "Quantum Computing" },
];