name: Build and deploy on Docker Hub Flask Server
on:
  push:
    branches:
      - main
    paths:
      - 'flask-server/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2 

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./flask-server
          file: ./flask-server/Dockerfile
          push: true
          tags: saiabhiramjaini/recruitizy-flask-server:latest

      - name: Verify Docker image
        run: docker pull saiabhiramjaini/recruitizy-flask-server:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull saiabhiramjaini/recruitizy-flask-server:latest
            sudo docker stop recruitizy-flask-server || true
            sudo docker rm recruitizy-flask-server || true
            sudo docker run -d -p 5000:5000 \
              -e PORT=${{ secrets.ENV_PORT }} \
              -e DATABASE_URL=${{ secrets.ENV_DATABASE_URL }} \
              --name recruitizy-flask-server saiabhiramjaini/recruitizy-flask-server:latest